import { COLORS, createThemedStyles } from "../../theme/colors";

export const styles = createThemedStyles(() => ({
  container: { flex: 1, backgroundColor: COLORS.backgrounds.screen },
  header: { padding: 16 },
  backButton: { flexDirection: "row", alignItems: "center", marginBottom: 8 },
  backText: { marginLeft: 4, color: COLORS.text.subtle },
  title: { fontSize: 24, fontWeight: "bold", marginBottom: 8 },
  categoryScroll: { flexDirection: "row", marginBottom: 12 },
  categoryButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.borders.muted,
    marginRight: 8,
  },
  categoryButtonActive: { backgroundColor: COLORS.blue, borderColor: COLORS.blue },
  categoryText: { color: COLORS.text.subtle },
  categoryTextActive: { color: COLORS.white },
  viewToggle: {
    flexDirection: "row",
    borderWidth: 1,
    borderColor: COLORS.borders.muted,
    borderRadius: 10,
    overflow: "hidden",
    marginBottom: 16,
  },
  toggleButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    gap: 4,
  },
  toggleButtonActive: { backgroundColor: COLORS.blue },
  toggleText: { color: COLORS.text.subtle },
  toggleTextActive: { color: COLORS.white, fontWeight: "600" },
  squadList: { paddingBottom: 20 },
  card: {
    flex: 1,
    margin: 4,
    backgroundColor: COLORS.backgrounds.elevated,
    borderRadius: 12,
    padding: 12,
  },
  playerPhotoWrapper: { position: "relative" },
  playerPhoto: { width: "100%", aspectRatio: 1, borderRadius: 12 },
  numberBadge: {
    position: "absolute",
    top: 4,
    right: 4,
    backgroundColor: COLORS.blue,
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  numberBadgeText: { color: COLORS.white, fontWeight: "bold" },
  playerName: {
    fontSize: 14,
    fontWeight: "500",
    marginVertical: 4,
    flexShrink: 1,
    flexWrap: "wrap",
    color: COLORS.text.blackWhite,
  },
  playerInfoRow: { flexDirection: "row", justifyContent: "space-between" },
  position: {
    backgroundColor: COLORS.blueTint,
    color: COLORS.blue,
    paddingHorizontal: 6,
    borderRadius: 6,
    fontSize: 12,
  },
  statsTable: { marginHorizontal: 16 },
  statsHeader: {
    flexDirection: "row",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borders.brandSoft,
    backgroundColor: COLORS.backgrounds.screen,
  },
  statsRow: {
    flexDirection: "row",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borders.brandSoft,
    alignItems: "center",
    backgroundColor: COLORS.backgrounds.screen,
  },
  playerInfo: {
    flex: 2,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    overflow: "hidden",
    minWidth: 0,
  },
  statsPhoto: { width: 50, height: 50 },
  statsText: {
    flex: 1,
    textAlign: "center",
    fontSize: 12,
    color: COLORS.text.blackWhite,
  },
  goalsText: { color: COLORS.blue, fontWeight: "600" },
  positionHeader: {
    width: "100%",
    paddingVertical: 4,
    paddingHorizontal: 8,
    marginTop: 8,
    borderRadius: 4,
  },
  positionHeaderText: {
    fontWeight: "bold",
    fontSize: 16,
  },

  statsHeaderButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  statsHeaderText: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.text.blackWhite,
    textAlign: "center",
  },
  modalContainer: {
    flex: 1,
    backgroundColor: COLORS.backgrounds.overlaySolid,
    justifyContent: "center",
    alignItems: "center",
  },

  fullImage: {
    width: "90%",
    height: "70%",
  },
  flex2: {
    flex: 2,
  },
}));
