import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fff" },
  header: { padding: 16 },
  backButton: { flexDirection: "row", alignItems: "center", marginBottom: 8 },
  backText: { marginLeft: 4, color: "#666" },
  title: { fontSize: 24, fontWeight: "bold", marginBottom: 8 },
  categoryScroll: { flexDirection: "row", marginBottom: 12 },
  categoryButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#ccc",
    marginRight: 8,
  },
  categoryButtonActive: { backgroundColor: "#3b82f6", borderColor: "#3b82f6" },
  categoryText: { color: "#666" },
  categoryTextActive: { color: "#fff" },
  viewToggle: {
    flexDirection: "row",
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 10,
    overflow: "hidden",
    marginBottom: 16,
  },
  toggleButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    gap: 4,
  },
  toggleButtonActive: { backgroundColor: "#3b82f6" },
  toggleText: { color: "#666" },
  toggleTextActive: { color: "#fff", fontWeight: "600" },
  squadList: { paddingBottom: 20 },
  card: {
    flex: 1,
    margin: 4,
    backgroundColor: "#f9f9f9",
    borderRadius: 12,
    padding: 12,
  },
  playerPhotoWrapper: { position: "relative" },
  playerPhoto: { width: "100%", aspectRatio: 1, borderRadius: 12 },
  numberBadge: {
    position: "absolute",
    top: 4,
    right: 4,
    backgroundColor: "#3b82f6",
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  numberBadgeText: { color: "#fff", fontWeight: "bold" },
  playerName: { fontSize: 14, fontWeight: "600", marginVertical: 4 },
  playerInfoRow: { flexDirection: "row", justifyContent: "space-between" },
  position: {
    backgroundColor: "#3b82f620",
    color: "#3b82f6",
    paddingHorizontal: 6,
    borderRadius: 6,
    fontSize: 12,
  },
  statsTable: { marginHorizontal: 16 },
  statsHeader: {
    flexDirection: "row",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderColor: "#ccc",
  },
  statsRow: {
    flexDirection: "row",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderColor: "#eee",
    alignItems: "center",
  },
  playerInfo: { flex: 2, flexDirection: "row", alignItems: "center", gap: 8 },
  statsPhoto: { width: 50, height: 50 },
  statsText: { flex: 1, textAlign: "center" },
  goalsText: { color: "#3b82f6", fontWeight: "600" },
  positionHeader: {
    width: "100%",
    paddingVertical: 4,
    paddingHorizontal: 8,
    marginTop: 8,
    borderRadius: 4,
  },
  positionHeaderText: {
    fontWeight: "bold",
    fontSize: 16,
  },

  statsHeaderButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  statsHeaderText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#666",
    textAlign: "center",
  },
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.9)",
    justifyContent: "center",
    alignItems: "center",
  },

  fullImage: {
    width: "90%",
    height: "70%",
  },
  flex2: {
      flex: 2,
    },
});
